language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t amitrii/docker-react -f Dockerfile.dev .

script:
    - docker run amitrii/docker-react npm run test -- --coverage